### ISSUE TITLE
securing root

### ISSUE THREAD

**Issue by sils** [greyltc/docker-archlinux-aur#1]
I do see a security risk in this line: https://github.com/l3iggs/docker-archlinux-aur/blob/master/Dockerfile#L13

Does it really make a difference for you? Especially with the OC image you derive this is more a security risk than useful.

**Comment by l3iggs** [comment]
Yeah this line obviously makes all users in the `wheel` group essentially equivalent to root.
There is one user in that group, the `docker` user, which I create one line below. I use that user to install and build packages in the Arch image because the all knowing arch devs recently removed the `--asroot` parameter from the package building system which allowed the root user to build non-standard packages from the arch user repository, an obvious prerequisite to installing them.

None of the internet facing services in the image are running under the `docker` user.

If there's some bug in owncloud/apache/php/whatever that lets an attacker escalate from the `http` user to some other user and run code from there, then I agree this line would become a real problem. Or if somehow an attacker gained the ability to add a user they control to the wheel group.

I'd wager that if an attacker can switch to an arbitrary user in the system or manipulate a user's groups, then they've probably already won and making wheel != root isn't going to make too much of a difference.

**Comment by l3iggs** [comment]
Would it make you feel better if I deleted the wheel group or the docker user or commented this line out just before starting apache & php in the owncloud image?

**Comment by sils1297** [comment]
Why do you change the docker user in the first place?

Your explanation sounds good I think a comment could keep further readers
calm. I'm not that much into your dockerfiles just wanted to mention it.
Am 30.03.2015 20:49 schrieb "l3iggs" <notifications@github.com>:
